[versions]

kotlin = "1.8.21"
cc-tweaked = "1.104.0"

# Forge dependencies
forge = "45.0.42"
forge-kotlin = "4.2.0"
parchment = "2023.03.12"
parchmentMc = "1.19.3"

# Build tools
changelog = "2.0.0"
curseForgeGradle = "1.0.11"
loom = "1.1.9"
forgeGradle = "6.+"
librarian = "1.+"
minotaur = "2.+"
#mixinGradle = "0.7.+"
#nullAway = "0.9.9"
quiltflower = "1.8.0"
spotless = "6.17.0"
#taskTree = "2.1.1"
vanillaGradle = "0.2.1-SNAPSHOT"

[libraries]
plugin-curseForgeGradle = { module = "net.darkhax.curseforgegradle:CurseForgeGradle", version.ref = "curseForgeGradle" }
plugin-loom = { module = "net.fabricmc:fabric-loom", version.ref = "loom" }
plugin-forgeGradle = { module = "net.minecraftforge.gradle:ForgeGradle", version.ref = "forgeGradle" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-librarian = { module = "org.parchmentmc:librarian", version.ref = "librarian" }
plugin-minotaur = { module = "com.modrinth.minotaur:Minotaur", version.ref = "minotaur" }
#nullAway = { module = "com.uber.nullaway:nullaway", version.ref = "nullAway" }
#quiltflower = { module = "io.github.juuxel:loom-quiltflower", version.ref = "quiltflower" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
plugin-vanillaGradle = { module = "org.spongepowered:vanillagradle", version.ref = "vanillaGradle" }
plugin-changelog = {module = "org.jetbrains.intellij.plugins:gradle-changelog-plugin", version.ref = "changelog"}

[plugins]
vanillaGradle = { id = "org.spongepowered.gradle.vanilla", version.ref = "vanillaGradle"}
loom = {id = "fabric-loom", version.ref = "loom"}